name: flutter_joystick
description: A virtual joystick widget for Flutter applications. Highly flexible and customizable.
version: 0.2.1
homepage: https://github.com/pavelzaichyk/flutter_joystick
repository: https://github.com/pavelzaichyk/flutter_joystick
funding:
  - https://paypal.me/pavelzaichyk
  - https://buymeacoffee.com/rebeloid
  - https://paypal.com/donate/?hosted_button_id=EG9DHRCSB5MY4

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
